// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bleojrsqfpcukhgdyjyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZW9qcnNxZnBjdWtoZ2R5anlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTMwMDQsImV4cCI6MjA2NjY4OTAwNH0.lPN75nsODLjWGXY_aCrLIXqpndgUU-34TPjQIDGHlTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);